name: JavaActions CI with Maven

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        options: --health-cmd='pg_isready' --health-timeout=30s --health-retries=5
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: solocali123#
          POSTGRES_DB: java_jenkins


    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Wait for PostgreSQL to be ready
        run: |
          until pg_isready -h localhost -p 5432 -U postgres; do
            echo "Esperando que PostgreSQL esté listo..."
            sleep 2
          done

      - name: Run Maven build
        run: mvn clean install -DskipTests=false
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/java_jenkins
          SPRING_DATASOURCE_USERNAME: postgres
          SPRING_DATASOURCE_PASSWORD: solocali123#

      - name: Build Docker image
        run: docker build -t java_jenkins_app .

      - name: Run Docker container
        run: |
          docker run -d -p 8080:8080 --name java_jenkins_app \
            -e SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/java_jenkins \
            -e SPRING_DATASOURCE_USERNAME=postgres \
            -e SPRING_DATASOURCE_PASSWORD=solocali123# \
            java_jenkins_app
